FROM registry.access.redhat.com/ubi9/python-311:latest

USER 0
WORKDIR /app

COPY backend/pyproject.toml .
COPY backend/src/ src/

RUN pip install --no-cache-dir . && \
    chown -R 1001:0 /app && \
    chmod -R g=u /app

COPY backend/alembic/ alembic/
COPY backend/alembic.ini .

USER 1001

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
