"""initial tables

Revision ID: 77441780e195
Revises: 
Create Date: 2026-03-31 10:54:54.827259
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77441780e195'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_trail_created_at', 'audit_trail', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_trail_user_id'), 'audit_trail', ['user_id'], unique=False)
    op.create_table('filter_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_rules_rule_type'), 'filter_rules', ['rule_type'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filtered', sa.Boolean(), nullable=False),
    sa.Column('filter_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_logs_created_at', 'search_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_logs_service'), 'search_logs', ['service'], unique=False)
    op.create_index(op.f('ix_search_logs_user_id'), 'search_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_logs_user_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_service'), table_name='search_logs')
    op.drop_index('ix_search_logs_created_at', table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_filter_rules_rule_type'), table_name='filter_rules')
    op.drop_table('filter_rules')
    op.drop_index(op.f('ix_audit_trail_user_id'), table_name='audit_trail')
    op.drop_index('ix_audit_trail_created_at', table_name='audit_trail')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
